name: demo3

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Log context obj
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: "echo GITHUB_CONTEXT: $GITHUB_CONTEXT"
